# Flutter build
variables:
  projectDirectory: 'ilogistics_TMS_mobile'
trigger:
- master
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: ;
  
    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: index.keystore
        apksignerKeystorePassword: ilog@2021
        apksignerKeystoreAlias: ilog@2021
        apksignerKeyPassword: ilog@2021
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: ''
    - task: PublishBuildArtifacts@1